package com.astro.entity.InventoryModule;

import lombok.Data;

import javax.persistence.*;
import java.time.LocalDate;
import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "goods_receipt_inspection")
public class GoodsReceiptInspection {

  //  @Id
 //   @Column(name = "gri_id")
  //  private String griId;

    @Id
    @Column(name = "gri_id")
    private String griId;

    @Column(name = "installation_date")
    private LocalDate installationDate;

    @Column(name = "commissioning_date")
    private LocalDate commissioningDate;

    @Column(name = "asset_code")
    private String assetCode;

    @Column(name = "additional_material_description")
    private String additionalMaterialDescription;

    @Column(name = "locator")
    private String locator;

    @Column(name = "print_label_option", columnDefinition = "BOOLEAN DEFAULT false")
    private boolean printLabelOption;

    @Column(name = "depreciation_rate")
    private double depreciationRate;


    private double bookValue;  //autogenerated value

    @Column(name = "attach_component_popup")
    private String attachComponentPopup;

    private String updatedBy;

    private String createdBy;

    private LocalDateTime createdDate = LocalDateTime.now();

    private LocalDateTime updatedDate = LocalDateTime.now();





}
